apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: sailsjs-gitops
    app.kubernetes.io/component: web
    app.kubernetes.io/instance: sailsjs-gitops
    app.kubernetes.io/name: sailsjs-gitops
    app.kubernetes.io/part-of: sailsjs-gitops
    app.openshift.io/runtime: java
  name: sailsjs-gitops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sailsjs-gitops
  template:
    metadata:
      labels:
        app: sailsjs-gitops
    spec:
      containers:
      - name: sailsjs-gitops
        imagePullPolicy: Always
        image: quay.io/readyhat/gitops-demo:v2
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 1337
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        ports:
        - containerPort: 1337
          protocol: TCP
        # - containerPort: 8443
        #   protocol: TCP
        # - containerPort: 8778
        #   protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 1337
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
